name: Production Release

on:
  push:
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      run: bash ./gradlew test

  apk:
    name: Generate APKs for UI tests
    needs: unitTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble app debug APK
        run: bash ./gradlew :buffer-android-app:assembleDebug
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew :buffer-android-app:assembleAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: Run UI tests on Firebase Test Lab
    needs: apk
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Download Android test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        run: gcloud config set project 
             ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation 
             --app app-debug/buffer-android-app-dev-debug.apk 
             --test app-debug-androidTest/buffer-android-app-dev- 
                    debug-androidTest.apk 
             --device model=Nexus6P,version=26,locale=en,
                      orientation=portrait

  buildAPK:
    name: Build Signed APK
    runs-on: ubuntu-latest
    needs: firebase
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Update release version
        run: |
          latest_release="$(git describe --match 
          '[0-9]*\.[0-9]*\.[0-9]*' --abbrev=0 --tags)"
          change_to="versionName "\"$latest_release"\""
          sed -i "0,/versionName/{s/.*versionName.*/$change_to/}" 
          app/build.gradle
      - name: Build .APK
        run: bash ./gradlew :app:assembleGooglePlay
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/googlePlay/release
          signingKeyBase64: ${{ secrets.APP_KEY }}
          alias: ${{ secrets.APP_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.APP_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.APP_KEY_PASSWORD }}
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ${{ env.SIGNED_RELEASE_FILE }}
      
  uploadAPK:
    name: Upload APK to Google Play
    runs-on: ubuntu-latest
    needs: buildAPK
    steps:
      - uses: actions/checkout@v2
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
         name: app-release
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.4
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH }}
          packageName: com.garyfimo.unittestexample
          releaseFile: app-release/app-googlePlay-release-unsigned-signed.apk
          track: production
          userFraction: 0.15
          whatsNewDirectory: whatsnew
