name: Production Release

on:
  push:
    tags:        
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      run: bash ./gradlew test
      
  buildAPK:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build .APK
        run: bash ./gradlew :app:assembleRelease
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.APP_KEY }}
          alias: ${{ secrets.APP_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.APP_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.APP_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ${{ env.SIGNED_RELEASE_FILE }}
      
  uploadAPK:
    name: Upload APK to Google Play
    runs-on: ubuntu-latest
    needs: buildAPK
    steps:
      - uses: actions/checkout@v2
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
         name: app-release
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.4
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_AUTH }}
          packageName: com.garyfimo.unittestexample
          releaseFile: app-release/app-release-unsigned-signed.apk
          track: production
          status: inProgress
          userFraction: 0.15
          whatsNewDirectory: whatsNew
